### Get all movies
GET http://localhost:3001/movies

###

### Get a specific movie by ID
GET http://localhost:3001/movies/679818f4af51eda63ff1f484

###

### Create a new movie (Bad Boys)
POST http://localhost:3001/movies
Content-Type: application/json

{
    "title": "Bad Boys",
    "description": "Two hip detectives protect a murder witness while investigating a case of stolen heroin.",
    "releaseDate": "1995-04-07",
    "genres": ["Action", "Comedy", "Crime"],
    "popularity": 8.7,
    "source": "Original Screenplay",
    "studio": "Columbia Pictures"
}

###

### Update an existing movie (Bad Boys)
PUT http://localhost:3001/movies/6795935fbc3844b95c3b6766
Content-Type: application/json

{
    "title": "Bad Boys",
    "description": "Two hip detectives protect a witness to a murder while investigating a case of stolen heroin from the evidence storage room from their police precinct.",
    "releaseDate": "1995-04-07",
    "genres": ["Action", "Comedy", "Crime", "Thriller"],
    "popularity": 9.0,
    "source": "Original Screenplay",
    "studio": "Columbia Pictures"
}

###

### Delete a movie by ID
DELETE http://localhost:3001/movies/6795935fbc3844b95c3b6766

###