### Get all employees
GET http://localhost:3000/products

###

### Get a specific movie by ID
GET http://localhost:3000/products/679818f4af51eda63ff1f484

###

### Create a new movie (Bad Boys)
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "Fresh Salmon Fillet",
  "description": "Premium-quality, wild-caught salmon fillet, sold per pound.",
  "price": 12.99,
  "category": "Seafood",
  "stock": 75,
  "storeId": "store004",
  "isAvailable": true
}

###

### Update an existing movie (Bad Boys)
PUT http://localhost:3000/products/67aa52ed96f13907317fc6bd
Content-Type: application/json

{
  "name": "Fresh Salmon Fillet",
  "description": "Premium-quality, wild-caught salmon fillet, sold per pound.",
  "price": 6.99,
  "category": "Seafood",
  "stock": 14,
  "storeId": "store004",
  "isAvailable": true
}

###

### Delete a movie by ID
DELETE http://localhost:3000/products/67aa52ed96f13907317fc6bd

###